// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKkdTiUHyBDLx_PVbHA-Z2yrdJZQxZCz0',
    appId: '1:181658751987:web:5c74aa421ee5dfa7067886',
    messagingSenderId: '181658751987',
    projectId: 'authentication--fb-bee3c',
    authDomain: 'authentication--fb-bee3c.firebaseapp.com',
    storageBucket: 'authentication--fb-bee3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NsBT2jXA6JCLoZIrwjpUVwEBX-mgCtY',
    appId: '1:181658751987:android:ba6157b1c1dcb08a067886',
    messagingSenderId: '181658751987',
    projectId: 'authentication--fb-bee3c',
    storageBucket: 'authentication--fb-bee3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpi6C5XlLmKG0ejFZPYDDvYb34ky6_zNA',
    appId: '1:181658751987:ios:e8ce653bfbf449b4067886',
    messagingSenderId: '181658751987',
    projectId: 'authentication--fb-bee3c',
    storageBucket: 'authentication--fb-bee3c.appspot.com',
    iosClientId: '181658751987-df8tfbvq1h7f09qem6en8ecq8c0d15hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleFacebook',
  );
}
